language: node_js
node_js:
- 8

branches: 
  only:
  - develop
  - master

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script:
  - npm run build

after_success: 
  - npm run release
